name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build all
        id: build
        uses: lokkju/github-action-sbt@master
        with:
          commands: build
      - name: Print duration
        run: echo 'The time was ${{ steps.build.outputs.time }}.'
